### ISSUE TITLE
Plans on offering a pre-built binary?

### ISSUE THREAD

**Issue by 32bitx64bit** [Ninad7n/AppLockFlutter#1]
Looks like a promising application but it has no pre-built binary nor any instructions on how to compile it.
Any plans?

**Comment by NinadKisan** [comment]
> Looks like a promising application but it has no pre-built binary nor any instructions on how to compile it. Any plans?

Checkout the releases.

**Comment by Ninad7n** [comment]
> Looks like a promising application but it has no pre-built binary nor any instructions on how to compile it.
> Any plans?

Checkout Releases
