### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by IM71** [Ninad7n/AppLockFlutter#2]
Hi
I can't get it installed on my phone, it shows "App not installed as package appears to be invalid".
Is there any workaround?

Thanks!

**Comment by Ninad7n** [comment]
Checkout app-debug.apk

**Comment by MohsinShahid052** [comment]
Hi, I am Mohsin Shahid from FAST National University in Pakistan, I am making a similar application to you that blocks or locks the application. But, we are facing some permission issues, so we wanted to try your application but we are facing some errors while running your application. Are there any dependencies that we want to fulfill before running your application?. Kindly guide us through that how can we run your application. Thank you.
