### ISSUE TITLE
Errors while running the application

### ISSUE THREAD

**Issue by MohsinShahid052** [Ninad7n/AppLockFlutter#5]
HI, i am Mohsin Shahid from FAST National University in Pakistan and I am currently doing my final year project along with some team members, we are making an application similar to yours but we were facing some issues. So, we wanted to try your application and get some ideas from it. While we try to run your application, we are facing some errors. Kindly guide us through that how can we run the application?. Are there any dependencies that we want to fulfill before running it?

**Comment by Ninad7n** [comment]
Please mention those error also
